SET CONCAT ~
SET PAUSE OFF
SET NEWPAGE NONE
SET HEADING OFF
SET FEEDBACK OFF
SET VERIFY OFF
SET LINESIZE 3000
SET TRIMSPOOL ON
SET TRIMOUT ON
SET LONG 50000
SET LONGC 50000

--SET WRAP ON

WHENEVER SQLERROR EXIT SQL.SQLCODE;
WHENEVER OSERROR EXIT FAILURE;

SET TERMOUT OFF

SPOOL &1

    SELECT RPAD(NVL(TO_CHAR(TARJETA), ' '),9,' ')|| TO_CHAR(FECHA,'YYYYMMDD')
    FROM    ITFCOLADM.T_SMV_MDM
    WHERE TRIM(TIPO_MOVIMIENTO) in ('2005','2006')
    AND TRIM(CONCEPTO) = '502'
    AND upper(RESULT) = 'OK'
    group by tarjeta, fecha
    order by tarjeta desc, fecha desc;

SPOOL OFF;


REM "Fin de fichero."
REM "Activo la salida estandar por si hay algun error para que se retorne a la variable de ERROR del proceso"
REM "que invoca el sql."
SET TERMOUT ON

EXIT;
